apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-list
spec:
  generators:
  - list:
      elements:
      - name: nginx
        cluster: in-cluster
        url: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
      - name: prometheus-operator
        cluster: in-cluster
        url: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
#  - git:
#      repoURL: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
#      revision: master
#      directories:
#      - path: applications/*
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
        targetRevision: HEAD
        path: 'applications/{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true

