apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  generators:
  - git:
      repoURL: "git@github.com:ElectrodeYT/argocd-multi-apps-itdesign.git"
      revision: HEAD
      directories:
      - path: applications/*
  template:
    metadata:
      name: "{{ path.basename }}"
    spec:
      project: default
      source:
        repoURL: "git@github.com:ElectrodeYT/argocd-multi-apps-itdesign.git"
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "argocd-{{ path.basename }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
