apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  labels:
    argocd.argoproj.io/instance: applicationsets
spec:
  generators:
#  - git:
#      repoURL: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
#      revision: master
#      directories:
#      - path: applications/*
  - list:
    elements:
    - name: nginx
  template:
    metadata:
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/ElectrodeYT/argocd-multi-apps-itdesign.git
        targetRevision: master
        path: 'applications/{{}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd-{{name}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true

